Member에 대한 인증을 구현
KTPT/Quna-server pull request #22
Opened 2021-01-20 14:15 UTC by toneyparky

resolve: #21 

간만에 재미있게 코딩을 했네요🙂
코멘트 많이 많이 남겨주시면 좋을 것 같습니다~~~

### notes
- 기존 `LoginMemberInterceptor`에서 `Member`를 반환하던 것을 `memberId`를 반환하여 객체 노출을 방지했습니다.
- 기존 `LoginMemberInterceptor`에서 인증과 멤버 정보 추출이라는 두가지 책임을 하던 것을 분리했습니다.
  - `LoginRequiredInterceptor`를 생성하였고 메서드에 붙는 어노테이션인 `LoginRequired`와 함께 동작하도록 구현하여 인증만을 담당하도록 처리했습니다.
  - 이 부분에서 두 인터셉터 모두 인증하는 부분이 들어가야 하기에 중복이 발생합니다. 어쩔 수 없다고 생각하는데 더 나은 방법이 있다면 참고해보겠습니다. 상속받고 메서드로 인증하는 부분을 메서드로 빼서 활용하는 방법이 갑자기 떠올랐네요.
- `Interceptor`에 대한 `Config`를 등록할 때에 `URL` 패턴으로만 필터링을 하고 `http method(POST, PUT...)`로 필터링을 할 수 없습니다. 그렇기에 모든 요청은 `Interceptor`를 통과하게 됩니다. 하지만 각 `Interceptor` 처음에 해당 요청이 특정 어노테이션을 가지고 있는지 검증하여 원하는 `api`에만 적용될 수 있도록 처리했습니다.
- 테스트에서 인증과 관련된 정보를 생성하는 부분의 중복이 발생하여 `AuthTestStep`으로 뺐습니다.
- rebase를 통해 최신 develop 브랜치와 머지될 수 있도록 처리했습니다.

감사합니다😬

2021-01-20 15:43 UTC, kouz95 requested changes
고생하셨습니다~ `@LoginRequired` 를 통해서 인증 인가를 구현하셨군요 👍
구현 잘해주셔서 큰 피드백은 없고 컨벤션 관련 밖에 없네요..

로그인 여부는 많은 요청들에 대한 수평적 관심사 이기 때문에 AOP로 해결해야되는 부분이고 AOP의 방식중 하나인 Interceptor를 사용하셨는데, LoginMemberId나 LoginRequired가 없는 요청도 전부 Interceptor를 탄다는 점에서 Interceptor는 정말 모든 요청에 필요한 검증만 사용해야하나? 라는 생각도 들긴 하네요.
존재하지 않는 경우 바로 탈출하는 로직이 있으니 큰 문제는 안될거라고 생각하지만, 만약 Aspect를 통해 직접 구현하는 방식이 비교되는 큰 장점이 있다면 고려해볼만 한 것 같습니다.

2021-01-20 15:43 UTC, kouz95 commented on quna/build.gradle
> +    implementation 'io.jsonwebtoken:jjwt:0.9.1'
`:0.9.1`은 없어도 될 것 같아요~~
```suggestion
    implementation 'io.jsonwebtoken:jjwt'
```

2021-01-20 15:43 UTC, kouz95 commented on quna/src/main/java/com/ktpt/quna/application/exception/InvalidTokenException.java
> +}
```suggestion
}

```
맨 끝에 공백 라인이 하나 있어야 할 것 같네요!

2021-01-20 15:43 UTC, kouz95 commented on quna/src/main/java/com/ktpt/quna/infra/LoginMemberIdInterceptor.java
> +}
```suggestion
}

```

2021-01-20 15:43 UTC, kouz95 commented on quna/src/main/java/com/ktpt/quna/infra/LoginMemberIdInterceptor.java
> +	private final JwtTokenProvider jwtTokenProvider;
```suggestion
    private final JwtTokenProvider jwtTokenProvider;
```

일부 파일에서 tab 사용한걸로 나오네요!

2021-01-20 22:46 UTC, toneyparky commented on quna/src/main/java/com/ktpt/quna/infra/LoginMemberIdInterceptor.java
> +	private final JwtTokenProvider jwtTokenProvider;
![image](https://user-images.githubusercontent.com/37579660/105250148-9bc09180-5bbc-11eb-8dd2-c4edf2801e96.png)
자동완성에서 포매팅을 할 때에 확인을 해보니 계속 걸리더라구요. 
4space를 해놓은 줄 알았는데 탭을 사용하고 있었나봅니다.
해당 부분을 경준님 pr에서도 수정해주셨으나 저도 수정해서 처리할게요~

2021-01-20 22:53 UTC, toneyparky commented on quna/src/main/java/com/ktpt/quna/infra/LoginMemberIdInterceptor.java
> +	private final JwtTokenProvider jwtTokenProvider;
![image](https://user-images.githubusercontent.com/37579660/105250810-b5aea400-5bbd-11eb-8f2f-20f88068782d.png)
요 부분이 저와 컨벤션이 조금 다른 것 같아요..!
tab관련한 부분도 우선은 커밋 안해두겠습니다. 만나게 되면 처리하죠!

2021-01-20 22:54 UTC, toneyparky commented on quna/src/main/java/com/ktpt/quna/application/exception/InvalidTokenException.java
> +}
좋은 지적이에요!
총 3군데에서 발견했습니다.
커밋은 안하고 수정만 해놓겠습니다😬

2021-01-20 22:54 UTC, toneyparky commented on quna/src/main/java/com/ktpt/quna/infra/LoginMemberIdInterceptor.java
> +}
👍

2021-01-20 22:57 UTC, toneyparky commented
저도 구현을 하다보니 모든 요청이 인터셉터를 거쳐야하니 아무리 초반에 early return 을 한다하여도 비효율이 발생한다는 생각이 들었네요.
다른 방안도 고려해서 더 나은 코드를 만들면 좋겠슴니다.

스프링 시큐리티를 적용하면 http method에 따라서도 허용 여부를 정할 수 있는 것으로 알고 있습니다. 하지만 시큐리티 자체도 많은 인터셉터나 필터를 사용하는 것이기에 비슷한 결과를 내지 않을까라는 생각도 적어봅니다. 
찾아서 공부해봐야겠네요. 

리뷰 감사해요~

2021-01-21 06:37 UTC, toneyparky commented
경준님께서 해당 pr을 pull한 후에 작업하셨고 현재 conflict가 나는데 두 pr을 수정하기가 불편하기에 경준님 pr #24 만 머지하기로 했습니다.
![image](https://user-images.githubusercontent.com/37579660/105301791-7e141c00-5bfe-11eb-9713-c9c87ae08c2c.png)

2021-01-21 06:50 UTC, closed without merging